spring:
  application:
    name: movie-catalog
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

jwt:
  secret: dev-secret-key-muito-longa-aqui-minimo-32-caracteres-0123456789
  expiration: 86400000

aws:
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_KEY}
  region: us-east-2
  s3:
    bucket: ${S3_BUCKET}