spring:
  application:
    name: movie-catalog
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: ${JWT_SECRET:uma_chave_temporaria_com_mais_de_32_caracteres_para_teste}
  expiration: 86400000

aws:
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_KEY}
  region: us-east-2
  s3:
    bucket: ${S3_BUCKET}